project_name: My Project Name
project_rulesets:
    - my_ruleset
file_extensions: php,php3,phtml
ignore_dirs:
    - /assets
    - /cache
    - /css
    - /data
    - /var
    - /vendor
    - /path/to/any/directory/to/ignore
include_dirs:
    - /src/Sculpin/Core/Configuration/
ignore_rules:
    - Structures/AddZero
rulesets:
  my_ruleset:
    - Structures/AddZero
    - Structures/MultiplyByOne
